In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("monday_crm_export.csv")

In [3]:
df.head()

,Accounts,Address,Alt Email,Category,Cell Phone,City,Comments,Contact Status,Country,Deal Name,...,Stage,Stage 2,State,Status,Subitems,Team Building Newsletter,Title,Type,Zipcode,link to Contact Us Page ES
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All,NaN,John Faustini,...,NaN,NaN,NaN,NaN,NaN,NaN,Chief Operating Officer,Lead,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Check,NaN,Daniella Spiegel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,All,NaN,Abbey Stafford,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,"Tampa, FL",NaN,All,USA,Abbie Perez,...,NaN,NaN,FL,NaN,NaN,NaN,NaN,Prospect,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Value,NaN,Abby Alido,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lead,NaN,NaN

In [4]:
d = {'subitems': None, 'person': '', 'mirror0': None, 'text89': 'Hello, Laura at the Laguna women’s club gave us your name as a wedding day coordinator for a reception at the women’s club! We don’t Could you give me your pricing for a day of coordination?', 'status8': None, 'email': 'stephaniejoystruck@gmail.com', 'text41': 'Wedding reception', 'text4': '', 'text47': 'Laguna women’s club', 'text86': "I don't Know", 'text6': 'Stephanie Struck', 'phone': '+13234208747', 'text__1': '', 'text81': '2a04:4e41:4602:2c::81c3:d02c', 'text8': 'Book Your Event 2023', 'text0': 'Organic search', 'date4': '2025-05-13 05:54', 'text3': 'Google', 'text1': 'www.google.com', 'text36': 'None', 'text62': 'https://eventsolutions.com/', 'text9': '/', 'text2': 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.4 Mobile/15E148 Safari/604.1', 'text': 'https://eventsolutions.com/contact-2/', 'text28': '23393', 'mirror_1': None, 'connect_boards': None, 'connect_boards6': None, 'connect_boards_1': None, 'connect_boards_15': None}

In [5]:
d.keys()

dict_keys(['subitems', 'person', 'mirror0', 'text89', 'status8', 'email', 'text41', 'text4', 'text47', 'text86', 'text6', 'phone', 'text__1', 'text81', 'text8', 'text0', 'date4', 'text3', 'text1', 'text36', 'text62', 'text9', 'text2', 'text', 'text28', 'mirror_1', 'connect_boards', 'connect_boards6', 'connect_boards_1', 'connect_boards_15'])